### PR TITLE
OIIOText: Get fonts using fontconfig

### PR DESCRIPTION
**Pull request by olear**
Use fontconfig to get fonts in combobox, only tested on Linux.
openfx-io-fontconfig-01
openfx-io-fontconfig-02

### CODE REVIEW

**Comment by olear** [comment]
Note that the font combobox is empty in Windows, due to missing font cache. Need to find a fix for that.

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/issues/14#issuecomment-96300223

**Comment by olear** [comment]
I'm closing this pull request, been testing fontconfig in Windows for some days and my conclusion is that using fontconfig in a plugin on Windows is not worth it.

Steps to use fontconfig on Windows:

 * I need to bundle fc-cache.exe and a 'fonts' folder
 * fc-cache.exe and 'fonts' must be copied to the hosts exe main folder, program files/inria/natron/bin
 * fc-cache.exe must run at least one time (this takes a long time on my computer with 3000+ fonts)
 * fc-cache.exe must rerun when new fonts are added, not slow but problematic:

The best possible integration would then be a 'update font cache' button in plugin, and that runs fc-cache.exe, but how are we going to readd fonts to the combobox?

Not good.

Found a function deep down in MagickWand that generates a good font list, and it works. Will add that to MagickText.

Will still use fontconfig on UNIX.

I know MagickText depends on ImageMagick, but Arena.ofx (MagickText+4 more plugins) is static and 6M on Win64 and 4.6M on Linux64. That should be acceptable?

**Comment by devernay** [comment]
Yes, we should bundle it with the Natron binaries

**Comment by devernay** [comment]
No dynamic libs un Arena.ofx? They could be shared with IO.ofx (jpeg, png, tiff, etc)

**Pull request closed without merging**
